local utils = require "astronvim.utils"
return {
  { "folke/tokyonight.nvim", lazy = false },
  {
    "catppuccin/nvim",
    optional = true,
    opts = {
      integrations = {
        alpha = false,
        lsp_trouble = true,
        notify = true,
        dashboard = false,
        flash = false,
        nvimtree = false,
        ts_rainbow = false,
        ts_rainbow2 = false,
        barbecue = false,
        indent_blankline = true,
        navic = false,
        dropbar = false,
        aerial = true,
        dap = { enabled = true, enable_ui = true },
        headlines = true,
        mason = true,
        native_lsp = { enabled = true, inlay_hints = { background = false } },
        neotree = true,
        noice = true,
        semantic_tokens = true,
        symbols_outline = true,
        treesitter_context = true,
        telescope = { enabled = true, style = "nvchad" },
        which_key = true,
        sandwich = true,
      },
    },
  },
  {
    "tpope/vim-fugitive",
    cmd = { "G", "Git", "Gdiff" },
  },
}
